#!/usr/bin/env python3
# @description - Output a uuid v4

from uuid import uuid4


def get_uuid():
    return uuid4()


def main():
    print(get_uuid(), end="")


if __name__ == "__main__":
    main()
